"""End-to-end validation of the certificate verification pipeline.

Drives the REAL application over HTTP (POST /api/verify) using the sample
certificates generated by scripts/generate_samples.py, then cross-checks
the persisted database records, the /api/verifications endpoint, feature
consistency with training, and /api/metrics.

Requires the backend to be running:
    uvicorn app.main:app --host 127.0.0.1 --port 8000

Usage (from backend/):
    python scripts/run_e2e_validation.py
"""

import json
import os
import pathlib
import sys

import httpx

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

BASE_URL = os.getenv("E2E_BASE_URL", "http://127.0.0.1:8000")
BACKEND = pathlib.Path(__file__).resolve().parent.parent
SAMPLES = BACKEND / "samples"

PASS, FAIL = [], []


def check(name: str, condition: bool, detail: str = "") -> None:
    (PASS if condition else FAIL).append(name)
    status = "PASS" if condition else "FAIL"
    print(f"[{status}] {name}" + (f" | {detail}" if detail else ""))


def post_verify(client: httpx.Client, filename: str) -> tuple[int, dict]:
    with open(SAMPLES / filename, "rb") as f:
        resp = client.post(
            f"{BASE_URL}/api/verify",
            files={"file": (filename, f.read(), "application/pdf")},
        )
    try:
        body = resp.json()
    except ValueError:
        body = {}
    return resp.status_code, body


def main() -> None:
    client = httpx.Client(timeout=60.0)

    # ------------------------------------------------------------------ #
    # 1. Health
    # ------------------------------------------------------------------ #
    h = client.get(f"{BASE_URL}/api/health")
    check("health 200", h.status_code == 200)
    check("health status ok", h.json().get("status") == "ok",
          f"model_loaded={h.json().get('model_loaded')}")

    model_info = client.get(f"{BASE_URL}/api/model/info")
    check("model/info 200", model_info.status_code == 200)
    mf = model_info.json().get("features", [])
    print(f"model/info: version={model_info.json().get('model_version')} "
          f"features={len(mf)}")

    # ------------------------------------------------------------------ #
    # 2. Feature consistency with training
    # ------------------------------------------------------------------ #
    from src.features.build_features import FEATURE_COLUMNS

    with open(BACKEND / "models" / "artifacts" / "features.json", "r", encoding="utf-8") as f:
        artifact_features = json.load(f)
    check("training schema 31 features", len(FEATURE_COLUMNS) == 31)
    check("artifact schema == training schema",
          list(artifact_features) == list(FEATURE_COLUMNS))

    from app.services.extraction_service import extract_document
    from app.services.feature_service import build_features_from_extraction

    ex = extract_document(str(SAMPLES / "genuine_certificate.pdf"), "pdf")
    runtime_features = build_features_from_extraction(ex)
    check("runtime feature keys == training schema",
          list(runtime_features.keys()) == list(FEATURE_COLUMNS))
    check("runtime feature count 31", len(runtime_features) == 31)
    numeric_ok = all(isinstance(v, (int, float)) for v in runtime_features.values())
    check("runtime feature values numeric", numeric_ok)

    # ------------------------------------------------------------------ #
    # 3. Verify each sample through the API
    # ------------------------------------------------------------------ #
    samples = [
        ("genuine_certificate.pdf", "genuine sample"),
        ("inconsistent_certificate.pdf", "inconsistent sample"),
        ("missing_security_certificate.pdf", "missing-security sample"),
        ("unusual_valid_certificate.pdf", "unusual-but-valid sample"),
        ("incomplete_certificate.pdf", "incomplete-info sample"),
    ]
    results = {}
    for filename, label in samples:
        status, body = post_verify(client, filename)
        check(f"{label} verify 200", status == 200, f"status={status}")
        for key in ("verification_id", "prediction", "risk_score", "confidence",
                    "model_version", "label", "message"):
            check(f"{label} has {key}", key in body)
        results[filename] = body
        print(f"  {label}: prediction={body.get('prediction')} "
              f"risk={body.get('risk_score')} conf={body.get('confidence')} "
              f"model={body.get('model_version')} id={body.get('verification_id')}")

    # ------------------------------------------------------------------ #
    # 4. Duplicate upload (repeat genuine) - must succeed without corruption
    # ------------------------------------------------------------------ #
    dup_status, dup_body = post_verify(client, "genuine_certificate.pdf")
    check("duplicate upload 200", dup_status == 200)
    check("duplicate upload new verification id",
          dup_body.get("verification_id") != results["genuine_certificate.pdf"]["verification_id"])

    # ------------------------------------------------------------------ #
    # 5. Failure cases
    # ------------------------------------------------------------------ #
    expected_reject = {
        "empty.pdf": (400, 422),
        "malformed.pdf": (400, 422),
        "unsupported.txt": (400,),
        "oversized.pdf": (400,),
    }
    for filename, expected in expected_reject.items():
        status, body = post_verify(client, filename)
        detail = body.get("detail", "")
        check(f"reject {filename} in {expected}", status in expected,
              f"status={status} detail={detail[:80]}")

    # ------------------------------------------------------------------ #
    # 6. Database persistence cross-check
    # ------------------------------------------------------------------ #
    from app.database.database import SessionLocal
    from app.models.verification import Verification

    db = SessionLocal()
    mismatches = 0
    try:
        for filename, body in results.items():
            record = (db.query(Verification)
                      .filter(Verification.verification_id == body["verification_id"])
                      .one_or_none())
            check(f"db record exists for {filename}", record is not None)
            if record is None:
                continue
            ok = (record.prediction == body["prediction"]
                  and round(record.risk_score, 4) == round(body["risk_score"], 4)
                  and round(record.confidence, 4) == round(body["confidence"], 4)
                  and record.model_version == body["model_version"]
                  and record.filename == filename)
            if not ok:
                mismatches += 1
            check(f"db record matches api for {filename}", ok)
    finally:
        db.close()
    check("all db records match api responses", mismatches == 0)

    # ------------------------------------------------------------------ #
    # 7. /api/verifications reflects the runs
    # ------------------------------------------------------------------ #
    vresp = client.get(f"{BASE_URL}/api/verifications")
    vlist = vresp.json()
    ids = {v["verification_id"] for v in vlist}
    for filename, body in results.items():
        check(f"/api/verifications contains {filename} id",
              body["verification_id"] in ids)

    # ------------------------------------------------------------------ #
    # 8. Monitoring metrics
    # ------------------------------------------------------------------ #
    mresp = client.get(f"{BASE_URL}/api/metrics")
    metrics = mresp.json()
    print("\n/metrics:")
    print(json.dumps(metrics, indent=2))
    check("metrics 200", mresp.status_code == 200)
    check("metrics has prediction_distribution",
          "prediction_distribution" in metrics)
    check("metrics total_verifications int",
          isinstance(metrics.get("total_verifications"), int))

    # ------------------------------------------------------------------ #
    # Summary
    # ------------------------------------------------------------------ #
    print(f"\nE2E RESULT: {len(PASS)} passed, {len(FAIL)} failed")
    for name in FAIL:
        print(f"  FAILED: {name}")
    if FAIL:
        raise SystemExit(1)


if __name__ == "__main__":
    main()